### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by itsUndefined** [locize/next-i18next-locize#3]
## 🐛 Bug Report

The  first example "POSSIBILITY 1: locize live download usage on client side only" does not appear to support server side rendering of the translations.

## To Reproduce

Run the example in this repository as is with JavaScript disabled on the browser.

## Expected behavior

I expected to see the example website rendered.

## Actual behavior

`loading translations...` is displayed and nothing happens.

## Your Environment

- *runtime version*:  node v18
- *os*:  Windows 11

**Comment by adrai** [comment]
Yes, if you like the delivered HTML already to be translated, have a look at the alternative usage:  https://locize.com/blog/next-i18next/#alternative-usage

**Comment by itsUndefined** [comment]
Alright. But then why does the same guide say that this very example should work on the server?
https://locize.com/blog/next-i18next/#That-39-s-it-Let-39-s-check-the-result
If it's no longer supposed to work like that could you please update the article?

**Comment by adrai** [comment]
Last year (with an older next.js version) it worked ;-)

**Comment by itsUndefined** [comment]
If it's no longer supposed to work like that could you please update the article? Locize is a paid product and I shouldn't have lost so much time trying to troubleshoot the issue thinking it was my fault.

**Comment by adrai** [comment]
Already on it
